create table if not exists refresh_tokens (
    id bigint generated by default as identity primary key,
    token_id varchar(64) not null unique,
    user_id bigint not null references users(id) on delete cascade,
    expires_at timestamp not null,
    created_at timestamp not null
);
